version: '3.1'
services:
  mongodb:
    build: ./mongodb_rs
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
      #ME_CONFIG_MONGODB_URL: mongodb://rootuser:rootpass@mongo:27017/
volumes:
 data: {}
networks:
  default:
    name: mongodb_network